name: Deploy

on:
  push:
    branches: [main]

# FireStone: Core Change 1 - Must grant permissions for the automation script to publish Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# FireStone: Core Change 2 - Ensure that only one deployment job runs at a time to avoid conflicts.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run check

      - name: Build
        run: pnpm run build
        env:
          SITE_URL: https://f1restone.github.io # FireStone: Core Change 3: Directly pass your website URL to the build tool

      # FireStone: Core Change 4: Upload the generated dist directory as a GitHub artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # FireStone: Core Change 5 - Add a separate deployment job that takes the artifact from the build job and deploys it to GitHub Pages.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4